package com.ono.ledger.enums

enum class DialogType {
    ACCOUNT_LEDGER_REPORT,
    CASH_BOOK,
    VOUCHER_PRINTING,
    SUPPLY_LEDGER,
    RETURN_LEDGER,
    NET_SALE_INVOICE_VENDOR_WISE,
    NET_SALE_R_INVOICE_VENDOR_WISE,
    STOCK_N_SALES_REPORT,
    BTR,
    TRANSACTION_SUMMARY
}